name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Paso 2: Conectar y ejecutar comandos en el servidor
      - name: Deploying to Server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.DEPLOY_TARGET_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.DEPLOY_PATH}}
            git pull origin main