name: Deploy to VPS

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Revisar el repositorio
      - name: Check out repository
        uses: actions/checkout@v2

      # Paso 2: Configurar SSH para acceder al servidor
      - name: Set up SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

      # Paso 3: Copiar archivos al servidor
      - name: Deploying to Server ${{ secrets.HOST_IP }}
        run: |
          ls -la /var/www/store/
          cd /var/www/store/wp-content/plugins
          git pull origin main