name: Deploy to VPS

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Revisar el repositorio
      - name: Check out repository
        uses: actions/checkout@v2

      # Paso 2: Configurar SSH para acceder al servidor
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Paso 3: Copiar archivos al servidor
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }} "cd ${{ secrets.DEPLOY_PATH }} && git pull origin main"