name: Deploy to VPS

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Paso 2: Conectar y ejecutar comandos en el servidor
      - name: Deploying to Server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.DEPLOY_TARGET_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /var/www/store/wp-content/plugins/ajax-product-details
            chown -R webadmin:www-data /var/www/store/wp-content/plugins/ajax-product-details
              
      
      - name: Sync files with rsync
        run: |
          rsync -avz --delete --exclude=".git" -e "ssh -p 22 -i ~/.ssh/id_rsa" ./ \
          ${{ secrets.SSH_USER }}@${{ vars.DEPLOY_TARGET_IP }}:/var/www/store/wp-content/plugins/ajax-product-details/